### ISSUE TITLE
Request for help - cygwin: Resolving a relative path to an absolute path

### ISSUE THREAD

**Issue by ksandom** [ksandom/shest#2]
## Task

- Either
  - [ ] Confirm that the current solution works.
  - [ ] Suggest a better solution
- [ ] Create a PR removing the `# TODO`, and adding the fix, if there is one.

## Background

I have code, that is largely derived from [here](https://stackoverflow.com/questions/1055671/how-can-i-get-the-behavior-of-gnus-readlink-f-on-a-mac). I don't have any way of testing this, so it would be great if someone could either confirm that it works as expected, or find a better solution that does work.

I'm keen to keep any solution light weight because this will be run on every invocation of a test, so a little weight will add up really quickly. If this proves problematic, I may later re-factor this to be derived at install time, and otherwise assumed when run from the clone directory.

```bash
    CYGWIN*)
        # TODO Could someone please confirm this works in cygwin? - https://github.com/ksandom/shest/issues/2
        export SHEST_SCRIPT="$(readlink -f "$0")"
    ;;
```

**Comment by ksandom** [comment]
Does [realpath](https://man7.org/linux/man-pages/man1/realpath.1.html) do it?
